# Generated by Django 4.2.4 on 2023-09-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={
                "ordering": ["order", "title"],
                "verbose_name": "Pagina",
                "verbose_name_plural": "Paginas",
            },
        ),
        migrations.AddField(
            model_name="page",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Orden"),
        ),
    ]
